### ISSUE TITLE
Recherche Verifikation Modell

### ISSUE THREAD

**Issue by peter-mueller** [peter-mueller/hm-modellbildung#1]
Welche Möglichkeiten können genutzt werden, um das Modell zu verifizieren?
z.B. Welche Plots? Welche Tests?

- Wie aussagekräftig sind die Möglichkeiten -> Priorisierung?
- Sind sie mit R oder Mathematica möglich?

**Comment by GrafDaniel** [comment]
um das hier mal zu sammeln: 
Hängt ja eng mit dem Kapitel "Überprüfung Normalverteilung" zusammen.
Grafische Optionen: Histogramm und QQ-Plot (Quantil-Quantil-Diagramm
Rechnerische Optionen: siehe DistributionFitTest -> TestDataTable
insbesondere: Shapiro-Wilk Test (von Fr. Köster empfohlen), Cramer-von-Mises Test (genau), Anderson-Darling (sehr genau)

Generell: Rechnerisch ist besser als grafisch, und selbst wenn ALLE FÜR Normalverteilung sprechen, hat man keinen Beweis/Gewissheit dafür. Müssen wir erwähnen..

Mit Mathematica sind alle möglich!
Kann man das hier zu machen?
