### ISSUE TITLE
Kriterien für Tests

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#104]
Test des Fast Marching: Konvergenzordnungstest 
-> Fast Marching soll gegen Euklid konvergieren (wenn sich Zelllänge halbiert, muss sich Fehler halbieren)

Test für Evakuierung: Mit identischen Personenzahlen muss sich die Evakuierungszeit beim Raum mit 4 Türen im Vgl. zum Raum mit 2 Türen halbieren

**Comment by Arne2** [comment]
Wurde berücksichtigt
