### ISSUE TITLE
Validierung

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#114]
Was sollen wir alles zur Validierunh schreiben?

Aktuell ist das Kapitel leer... 

RIMEA würde ich rein tun (Fundamentaldiagramm kann man ja gegen prüfen)
Was noch?

**Comment by dalmadima** [comment]
Ja Also auf jeden Fall das Fundamentaldiagramm und den Personenfluss

**Comment by dalmadima** [comment]
Vielleicht kann man auch sagen, dass man "optisch" validiert... Also  es sieht aus als würden sich echte Menschen bewegen
Aber dann Erwähnen, was überhaupt nicht der Realität entspricht.

**Comment by GrafDaniel** [comment]
@peter-mueller  sollen wir noch ne Absatz über quntitative bzw. optische Validierung ergänzen? so quasi vor Rimea wurde es optisch schon grob überprüft?

**Comment by Arne2** [comment]
Könnt Ihr den Teil im Fazit bitte noch anpassen?

**Comment by dalmadima** [comment]
optische Validierung lassen wir jetzt weg.
