### ISSUE TITLE
Seminararbeit 7 Ermitteltes Modell

### ISSUE THREAD

**Issue by Arne2** [peter-mueller/hm-modellbildung#18]
Die Beschreibung des ermittelten Modells.

**Comment by Arne2** [comment]
Ist die Frage, ob wir das brauchen...

**Comment by GrafDaniel** [comment]
Ich verstehe nicht ganz was damit gemeint ist? Wir haben hier doch nicht wirklich ein Modell ermittelt? Das "Regressionsmodell" ist ja schon in den anderen Kapiteln drinnen, in denen sie berechnet werden

**Comment by peter-mueller** [comment]
Ich hab mit dem Modell so gemeint, dass bei Regression einfach alle Regressionen berechnet und beschrieben werden. In diesem Kapitel sollten sie dann verglichen werden und zum Schluss geschrieben welche Gleichung wir wählen und warum die genau die beste ist. Das könnte man auch Ändern.

Geplant war:
Regression: Stumpfes ausrechnen
Modell: Beschreibung wieso was gewählt wurde

**Comment by Arne2** [comment]
Wird nicht gebraucht.
