### ISSUE TITLE
Seminararbeit 8 Vergleich mit 2012

### ISSUE THREAD

**Issue by Arne2** [peter-mueller/hm-modellbildung#19]
Enthält:
 - Normalverteilung
 - Lineare Regression
 - Vergleich

**Comment by GrafDaniel** [comment]
Habe die Lineare Regression (mehrere Parameter) für 2017 und 2017 durchlaufen lassen und an Peter geschickt. Beim Vergleich/ Bei der Auswertung muss darauf geachtet werden, dass die 2012 beim Messen einiges verbockt haben ... evtl sollte man bereinigte/gefilterte Werte für 2012 nehmen.. Da ist gefühlt jedes 3. Messergebnis beim Treppensteigen etweder "gerannt" oder "vergessen zu stoppen" oder sonstige Annomalien
