### ISSUE TITLE
Seminararbeit 9 Verbund alter und neuer Daten

### ISSUE THREAD

**Issue by Arne2** [peter-mueller/hm-modellbildung#20]
Der Verbund alter und neuer Daten

**Comment by dalmadima** [comment]
was ist damit gemeint, verbund alter und neuer daten? sollen die Daten von 2012 und 2017 in eine Datei?

**Comment by Arne2** [comment]
#### 2.4    Zusatzaufgabe für Viererteams: Vereinen der Experimente von 2012 und 2017
Kann man das Exeriment von 2017 sinnvoll mit dem von 2012 vereinen und eine Gesamtauswertung machen? Wenn nein, warum? Wenn ja, was ergibt die gemeinsame Auswertung?

**Comment by dalmadima** [comment]
Ja habs grad gelesen... Die Köster hatte das PDF mit der angabe ja geändert gehabt in der Zwischenzeit. ich hatte noch die alte Version. Genau das Selbe wie mit der QR zerlegung.
