### ISSUE TITLE
Seminararbeit 10 Fazit

### ISSUE THREAD

**Issue by Arne2** [peter-mueller/hm-modellbildung#21]
Das Fazit soll beschrieben werden.

**Comment by GrafDaniel** [comment]
Mein Vorschlag: 
Ziel dieser Arbeit war es zu überprüfen, ob ein Zusammenhang zwischen der Wunschgeschwindigkeit einer Person in der Ebene und der Geschwindigkeiten beim Treppensteigen besteht. Dabei wurde das Laufverhalten sowohl beim Treppenaufstieg als auch beim Treppenabstieg betrachtet. Es wurden, wie im Kapitel XXX erläutert, Messreihen durchgeführt und die ermittelten Daten daraufhin auf Normalverteilung untersucht. Anschließend wurde die lineare Regression verwendet um mögliche Zusammenhänge zwischen den Treppengeschwindigkeiten und den Parametern der Probanden, wie Ebenengeschwindigkeit, Körpergröße oder der Rundennummer zu erkennen. Mithilfe der t-Tests wurden die resultierenden Werte auf Plausibilität geprüft. Dabei wurde entschieden ob es Abhängigkeiten gibt. Zur Überprüfung der Relevanz dieser Beobachtungen wurde die Konditionierung des Problems untersucht. Die gewonnenen Erkenntnisse wurden mit Messdaten aus einem, bereits im Jahr 2012 durchgeführten, Experiments verglichen und verbunden. 

Die Ergebnisse der Untersuchungen ergaben, dass die Treppengeschwindigkeit eines Probanden sehr wahrscheinlich von der Wunschgeschwindigkeit in der Ebene abhängig ist. Verbindungen zwischen der Treppengeschwindigkeit und der Körpergröße bzw. der Rundennummer konnten nicht gefunden werden.

Die Resultate dieser Arbeit können keine 100\%tige Aussage über das Laufverhaltens eines Menschen auf einer Treppe auf Basis der Wunschgeschwindigkeit in der Ebene treffen. Für solch eine Vorhersage ist das Laufverhalten von Personen noch nicht ausreichend untersucht. Für noch genauere Ergebnisse und Vorhersagen würden sich zukünftige Messreihen mit wesentlich mehr als $22$ Probanden anbieten. 

Evtl noch 2 Sätze was nun normalverteilt ist und was nicht, oder meinst du das braucht man nicht?

**Comment by Arne2** [comment]
Wenn du einzelne Änderungen vorschlägst, ist es einfacher was anzupassen.
