### ISSUE TITLE
Latex Vorlage

### ISSUE THREAD

**Issue by peter-mueller** [peter-mueller/hm-modellbildung#3]
Vorlage für die erste Abgabe erstellen.

**Comment by peter-mueller** [comment]
Einverstanden? Zwei Spalten ok?

- [ ] @Arne2 
- [ ] @dalmadima 
- [ ] @GrafDaniel

**Comment by Arne2** [comment]
Ich finds hart hässlich. Außerdem wirds dann auch lustig, wenn wir Bilder einsetzen wollen.

**Comment by Arne2** [comment]
Gelöst durch #11
