### ISSUE TITLE
Auswertung der Ergebniswerte

### ISSUE THREAD

**Issue by peter-mueller** [peter-mueller/hm-modellbildung#40]
Mathematisch mit Theorem von Little um das Programm zu validieren. 

Die Ergebnisse vom Theorem können auch schon fertig sein bevor das Programm fertig ist.

**Comment by dalmadima** [comment]
Ermittlen Sie die Werte für die
• mittlere Warteschlangenlänge
• mittlere Anzahl von Kunden im Shop
• mittlere Anstehzeit
• mittlere Verweildauer im Shop
• mittlere Serverauslastung
und stellen Sie sie im Zeitverlauf dar. Kommentieren Sie Ihre Ergebnisse. Verwenden Sie das Theorem von Little, um
Ihr Programm zu validieren. Visualisieren Sie ihre Ergebnisse mit geeigneten Grafiken.

**Comment by dalmadima** [comment]
Sehr geehrter Herr Diez,

die Auswertungen können im Prinzip in einem externen Tool gemacht
werden, sofern das auch für lange Experimente klappt.
So müssen Sie ja sehr viele Werte übergeben, vermutlich in einem File.
Es sei denn sie rufen den Java-Code aus Mathematica auf (was geht).
Da können Sie, wenn sie über lange Zeiten simulieren, an ihre Grenzen
stoßen.

Fragen Sie bitte nochmal am Mittwoch, damit ich die Antwort allen gebe.

Mit freundlichen Grüßen
Gerta Köster

On 07.05.2017 20:20, Dimitrie Diez wrote:
> Sehr geehrte Frau Köster,
>
>
> Wir sind uns nicht sicher bzw. uneinig was genau unser Java Code
> ausrechnen soll.
>
> Im Moment haben wir ein funktionierendes Warteschlangensystem. Wir geben
> die Ankunftszeiten und die Telefonierzeiten und die Warteschlangenlänge
> aus.
>
> Diese Zeiten werten wir in Mathematica aus und berechnen z.B. die
> mittlere Warteschlangengröße, die mittlere Wartezeit usw.
>
>
> Sollen wir diese Berechnungen (mittlere Wartezeit usw...) ebenfalls in
> Java implementieren?
>
>
> Mit freundlichen Grüßen
>
>
> Dimitrie Diez
>


-- 
__________________________________________________________
Prof. Dr. Gerta Köster
Hochschule München/Munich University of Applied Sciences
Lothstr. 64
80335 München
__________________________________________________________
Ceterum censeo Europam esse aedificandam.
(Joseph Bech, 1957)

**Comment by dalmadima** [comment]
http://www.business.uzh.ch/dam/jcr:00000000-0451-792f-ffff-fffffe13aac9/ServiceManagement_Warteschlangenmodelle.pdf

Seite 7.. Da sind Formeln für die Berechnung... also wir können quasi einen Erwartungswert berechnen... und dann Unsere Simulation dagegen prüfen

**Comment by Arne2** [comment]
closed by #66
