### ISSUE TITLE
Implementierung ein Telefon

### ISSUE THREAD

**Issue by peter-mueller** [peter-mueller/hm-modellbildung#42]

**Comment by dalmadima** [comment]
Folgende Angaben haben Sie vom Betreiber des Callshops erhalten:
• Im Mittel betritt alle 1000 s ein Kunde den Laden.
• Im Mittel telefonieren die Kunden 100 s.
• In der Hauptsaison verzehnfacht sich die Anzahl der Dorfbewohner.
Was beobachten Sie?
