### ISSUE TITLE
Queuelength ++  bei freiem Telefon

### ISSUE THREAD

**Issue by Arne2** [peter-mueller/hm-modellbildung#53]
Ein neuer Kunde kommt in einen Laden und kann gleich Telefonieren. Dabei soll er nicht die Queue betreten, sondern direkt das Telefon belegen.

**Comment by peter-mueller** [comment]
Ich finde schon das er für 0 Sekunden in der Queue sein sollte

**Comment by GrafDaniel** [comment]
das war genau das was wir Mittwoch mit ihr besprochen hatten und sie auch nicht haben wollte. Denn er ist faktisch NICHT in der Warteschlange. das Integral darüber ist 0.

**Comment by Arne2** [comment]
Wird nicht geändert.
