### ISSUE TITLE
Überprüfung Code <-> Requirements

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#57]
Überprüfen dass Code mit den Requirements übereinstimmt!

**Comment by Arne2** [comment]
"arrival_distribution.csv" und "serve_distribution.csv" anstelle ...Rand.csv
für die Parameter siehe #52 
Modi stimmen

**Comment by dalmadima** [comment]
ok

**Comment by Arne2** [comment]
closed by #66
