### ISSUE TITLE
Zellaufteilung (Arbeiten Sie mit den Zellmittelpunkten!)

### ISSUE THREAD

**Issue by dalmadima** [peter-mueller/hm-modellbildung#67]
Zellaufteilung (Arbeiten Sie mit den Zellmittelpunkten!)

Zellbreite sind 50

Frage? 
es gibt 8 Bewegungsrichtungen? sind alle Felder gleich weit entfernt?
o o o
o x o
o o o

Also auch die Diagonalen?

Ich würde sagen ein 100 x 100 Feld für den Anfang?

**Comment by peter-mueller** [comment]
50cm
Die diagonalen sind weiter weg wurzel2 * 50

**Comment by dalmadima** [comment]
CLOSE: fertig Implementiert. Die Zellgröße wird über Parameter übergeben
