### ISSUE TITLE
Ausgabe (in Datei) von: Zeit („Realzeit“), Person, Ort, momentate Geschwindigkeit

### ISSUE THREAD

**Issue by dalmadima** [peter-mueller/hm-modellbildung#70]
Ausgabe (in Datei) von: Zeit („Realzeit“), Person, Ort, momentate Geschwindigkeit (z.B. gleitende Mittel). Gestalten sie die Ausgabe so, dass sie zumindest einen Schnappschuss bekommen, sobald sich eine signifikante Veränderung ergeben hat: Größenordung 1 sec, denn bei einer mittleren Wunschgeschwindigkeit von z.B. 1,3 m/s wollen ihre Personen sich in einer Sekunde über einen Meter bewegen.

**Comment by Arne2** [comment]
Done
