### ISSUE TITLE
Erste Gehversuche

### ISSUE THREAD

**Issue by dalmadima** [peter-mueller/hm-modellbildung#73]
Also kleines Update, habe heute mit Frau Köster gesprochen.

1. Es gibt KEINE parallele Abarbeitung der Events... Das heißt die Personen ziehen der Reihe nach.
Dadurch können wir Kollisionen ausschließen
1.1 Die Reihenfolge der Personen, also er zuerst ziehen darf müssen wir entscheiden. --> eine Möglichkeit. Wer zuerst "geboren" wurde, der darf zuerst ziehen. 
1.2 Die Wunschgeschwindigkeit der Personen muss nach Möglichkeit eingehalten werden. Köster: Man könnte bei jeder Person ein Konto einrichten, ob er denn die Wunschgeschwindigkeit hat. geht er im ersten zug zu langsam, kann er im nächsten zug schneller gehen usw. ..Muss er stehen bleiben, z.B. weil eine Person vor Ihm ist, dann beeinflusst das seine Wunschgeschwindigkeit nicht... Heißt er muss danach nicht schneller gehen, weil er eine Runde ausgesetzt hat.

2. Zeit: Man könnte eine Feste Zeit einrichten (nicht schön). oder Event driven. 
Mein Vorschlag 1: die schnellste Person gibt die Zeit vor. also den Takt.
Mein Vorschlag 2: Jede Person generiert ein Event "GO".. Die zeit für das Event "GO" = Time(now) + (Zeit die er für 50cm bräuchte).. Die events werden in einer Liste abgearbeitet.

3. Wir haben ein Rechteckiges Muster:
o o o 
o x o
o o o
Die Diagonale ist tatsächlich weiter weg.

**Comment by peter-mueller** [comment]
1.1 personen werden ins feld gesetzt, ganz am anfang ist das die reihenfolge wie sie abgearbeitet werden. 
1.2 personen laufen immer nur eine zelle, je nach dem wie weit die zelle weg ist, wird ein neues event in der zeit die das laufen eben benötigt erstellt. TODO: findet eine person keine freie zelle ist unklar wie lang sie warten soll um wieder zu schauen (zeit bis nächtes event)  es gibt aktuell kein konto

2. event driven, vorschlag 2 (zeit für 50cm bzw. zeit für 50*wurzel(2))

**Comment by peter-mueller** [comment]
test für freier fluss kann man sich schon anschauen als junit test und in der main ist ein beispiel mit wänden

**Comment by peter-mueller** [comment]
für die nutzen berechnung fehlt noch der euklidische abstand, aber der sollte sehr leicht analog zum dijkstra mit einer map einfügbar sein

**Comment by dalmadima** [comment]
Hmm ehrlich gesagt ich weiß nicht, wie wir das "gut" lösen wollen. Weil du ja jetzt Jedes mal events anlegst.. Die jedes mal angelegt werden. 
Wir könnten eine Liste Mit Personen anlegen, welche auf ein freies Feld warten. Diese Liste musst du durchgehen, bevor du ein Feld verlässt. Falls eine Person auf dieses Feld warte, dann lege ein Event an.... 

Problem: Falls zwei personen sich direkt gegenüberstehen und entgegengesetzt laufen wollen, dann gibts nen deadlock. (Sollte bei uns nicht passieren)
