### ISSUE TITLE
Diskussion: Sinnhaftigkeit des Personal Space

### ISSUE THREAD

**Issue by dalmadima** [peter-mueller/hm-modellbildung#76]
In [7] wird eine noch wesentlich feinere Funktion vorgeschlagen, die das unter Psychologen anerkannte
Modell für „personal space“ von Hall [3] abbildet. Macht diese Verfeinerung für Ihren Zellularautomaten
Sinn? (Gute Diskussion gibt Zusatzpunkte)

**Comment by peter-mueller** [comment]
ist glaub klar jetzt
