### ISSUE TITLE
Personenpotenzial

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#79]
(a) Personen verringern ihren Nutzen, wenn sie sich zu nahe kommen.
(b) In der physikalischen Analogie „trägt“ jede Person ein Abstoßungspotenzial mit sich herum.
(c) Bewegung in der Menge: Jede Person bestimmt den Nutzen in den Nachbarzellen der von-Neumann-
Umgebung. Dabei addiert die Person den Nutzeneinfluss aller Personen in einer geeigneten Umgebung der
betrachteten Nachbarzelle zum Zielnutzen in der Nachbarzelle. Eine (erste) geeignete Umgebung besteht
aus zwei Ringen um die Nachbarzelle

**Comment by dalmadima** [comment]
Siehe: 
https://github.com/peter-mueller/hm-modellbildung/issues/75

**Comment by dalmadima** [comment]
Mach vielleicht paar tolle Grafiken für die Doku...
Feld Ohne Personenpotenzial.. Feld MIT Personenpotenzial
