### ISSUE TITLE
Studarbeit: Anforderungen

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#84]

**Comment by dalmadima** [comment]
3.7 Zeitmodellierung
Die Applikation unterliegt keinen harten Echtzeitanforderungen. Die Simulation soll für
die gesamte Simmulationsdauer so schnell wie möglich durchgeführt werden. Es soll keine
Globale Uhr modelliert werden.


Ich finde da muss zwischen Simulation und Visualisierung unterschieden werden.
Simulation: unterliegt keinen Echtzeitanforderungen
Visualisierung: unterliegt Echtzeitanforderungen

Die Visualisierung der Simulation muss schon in Echtzeit dargestellt werden können.

**Comment by dalmadima** [comment]
Die Tabelle 1 zeigt alle möglichen Parameter, welche die Software steuern. Alle Parameter
sind optional.

Bitte Parameter ausfüllen:
--free-flow-velocity
--free-flow-deviation
--algorithm
--output-folder
--cellsize
--input-map

**Comment by GrafDaniel** [comment]
ok danke werde beides ergänzen/ ändern. 
Hab gestern schon mal was in Slack geschrieben: Ich habe keinen Zugriff auf die Paper, auf welche Fr. Köster in der Angabe verweist (v. a. bzgl Abstoßungspotenzial der Personen)

**Comment by dalmadima** [comment]
PS: Wenn du Anforderungen definierst, dann solltest du die Anforderungen auch wirklich definieren. Heißt.. wenn du es für Sinnvoll hälst ein Parameter hinzuzufügen, dann mach das. Die Anfordungen definieren die Software, nicht umgekehrt.

Defaultwerte bitte einfügen

**Comment by dalmadima** [comment]
Die Software hat 3 Betriebsmodi. Abhängig vom Betriebsmodus wird der Nutzen
bzw. die Attraktivität der einzelnen Zellen, bezogen auf das/die Ziel(e) mit anderen
Algorithmen berechnet.... Finde die Bezeichung nicht gut. Es sind ja keine wirklichen Betriebsmodi.. Es wird lediglich ein andere Algorithmus verwendet. 

Würde das Kapitel: "Berechung des Zielnutzen" .. oder "Zielnutzen Algorithmus" oder sowas nennen...
Ist jetzt aber meine subjektive Meinung

**Comment by dalmadima** [comment]
3.12 Werte für die Auswertung
Alle in der Tabelle 2 aufgeführten Werte sollen auf Basis der Simulation ermittelt und
ausgewertet werden. Einige Werte wer . . . 


Bitte Tabelle anpassen ;)

**Comment by GrafDaniel** [comment]
du Dima ich hab im Latex File noch jede Menge TODOs drinnen ;) Sprich ich bin noch ned fertig :D in den Commits steht immer was (meiner Ansicht nach) fertig ist

**Comment by GrafDaniel** [comment]
3 Anmerkungen:
1. Im Kapitel Personen fehlt noch die Begründung warum genau diese Funktion genommen wird (kann ich wg fehlenden Zugriff auf das Paper nicht machen) 
2. Kapitel Report: Damit warte ich noch bis das alles fix ist - bzw ist es das schon? 
3. Die Tests habe ich ziemlich ausführlich beschrieben - soll das alles so bleiben oder soll das in ein extra Kapitel ausgelagert werden? Was meint ihr?
