### ISSUE TITLE
Aufteilung der Arbeit

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#88]
Sie möchte z.B in einem extra Kapitel aufgeführt haben wer was gemacht hat (wenn etwas von 2 Personen implementiert wurde (Zitat: "umso besser") dann sollen wir das hinschreiben.

Aufgegliedert nach: Theorieteil und Implementierung

**Comment by dalmadima** [comment]
Peter deine Aufgabenverteilung fehlt noch:

Branch: SemArbeitAufgabenverteilung

**Comment by GrafDaniel** [comment]
done
