### ISSUE TITLE
Visualisierung: Auflösung und Maßstab

### ISSUE THREAD

**Issue by dalmadima** [peter-mueller/hm-modellbildung#92]
Was wir unbedingt beachten sollten, bei der Visualisierung ist der Maßstab.

Im Moment haben wir ja recht kleine Simulationen mit wenigen Felden. In der Visualisierung haben wir dann Extrem große "pixel".

Vorschlag 1: Feste Zellgröße (in pixel) vorgeben. z.B. 2pixel pro zelle. die Feldgröße ist dann variabel.
Berechnung.. 100 m Entfernung.. bei Feldgröße von 0,5m/Feld. heißt 200 Felder.
Bei 2pixel Pro Feld = 400 Pixel Breite:

Vorschlag 2: Die Zellgröße (in Pixel) ist abhängig von der Anzahl der Felder. Das Feld ist auf eine Größe von z.B. 800x800 px fixiert.
Beispiel: 100m entfernung.. Bei Feldgröße von 0,5m/Feld. sind  200 Felder:
800pixel breite / 200 Felder = 4Pixel/Feld

Was sagt Ihr?

**Comment by GrafDaniel** [comment]
Vorschlag 1: Ist denke ich Problematisch weil die Zelle ja quadratisch sein muss also wenn dann 1 oder 4 Pixel pro Zelle
Vorschlag 2: Finde ich besser, die Frage ist jedoch ob es notwenig ist, da wir ja FESTE Szenarien haben, die wir simulieren soll (z.B Ihre Tests, in Anforderungen habe ich noch welche ergänzt)

**Comment by dalmadima** [comment]
hab mich evtl falsch ausgedrückt.. eine Zelle mit 2pixel mein ich natürlich eine 2x2 pixel zelle...


Vorschlag 2 ist problematisch wenn man verschiedene Karten vergleichen will.. Dann ist der Maßßstab immer anders ;)

**Comment by Arne2** [comment]
Ich lass mir vom output.xml die Zellengröße mitgeben (Was gerade 40cm ist) Und stelle das dann in der Legende der Gui dar.

**Comment by dalmadima** [comment]
Bis wann schaffst du es, dass der Richtige Maßstab in der Gui dargestellt wird? und auch die Farbzuordnung.. Als eine Farbskala, wo steht, welche Farbe welchen Abstand bedeutet

**Comment by Arne2** [comment]
closed by #107
