### ISSUE TITLE
Report - Geschwindigkeiten der Personen

### ISSUE THREAD

**Issue by GrafDaniel** [peter-mueller/hm-modellbildung#99]
Wie sollen wir das Lösen?
In den Anforderungen habe ich geschrieben dass in einer velocity.csv die individuellen Wunschgeschw. der Personen stehen sollen. Doch was ist mit den tatsächlichen Geschwindigkeiten?

Vorschlag: Sobald eine Person im Ziel ist wird ihre durschnttliche Geschwindigkeit in ein .csv gespeichert? DIe Frage ist nur wie ist das beim Rimea4 Test?

**Comment by Arne2** [comment]
Über Measurement Field gelöst
